#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar               all:40:0       \
                mouse_follows_focus        off            \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             on             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.8            \
                window_animation_duration  0.5            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                10              \
                bottom_padding             10              \
                left_padding               10              \
                right_padding              10              \
                window_gap                 10

# exclude problematic apps from being managed:
yabai -m rule --add app="^(calculator|software update|dictionary|vlc|system preferences|system settings|zoom.us|photo booth|archive utility|python|app store|steam|activity monitor|discord)$" manage=off
yabai -m rule --add label="finder" app="^finder$" title="(co(py|nnect)|move|info|pref)" manage=off
yabai -m rule --add label="safari" app="^safari$" title="^(general|(tab|password|website|extension)s|autofill|se(arch|curity)|privacy|advance)$" manage=off
yabai -m rule --add label="about this mac" app="system information" title="about this mac" manage=off
yabai -m rule --add label="create a new image" app="^gimp$" title="create a new image" manage=off
yabai -m rule --add label="about gimp" app="^gimp$" title="about gimp" manage=off
yabai -m rule --add label="^change foreground color" app="^gimp$" title="^change foreground color" manage=off
yabai -m rule --add app="^gimp$" title="^welcome to gimp" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
